### ISSUE TITLE
[Bug] Layout / UI Issue

### ISSUE THREAD

**Issue by OwenMelbz** [sanity-io/orderable-document-list#10]
Hi,

Just installed, everything seemed to run pretty smoothly, however we have a strange UI issue with the button to edit the document.

![image](https://user-images.githubusercontent.com/1094740/141775070-30ae0343-00b4-4ede-b98a-41ab297fab2e.png)

As you can see the arrow alignment is a little off, I've checked our custom css incase we've got a clash and we only have this

```css
:root {
  --brand-primary: #FF5900;
  --brand-primary--inverted: #FFFFFF;
}
```

Any advise?

Thanks
